Add PHP 5.6, 7.0 and 7.1 to travis build and allow them to fail
AKSW/Erfurt pull request #131
Opened 2016-11-01 15:20 UTC by white-gecko

This allows us to also test against later versions but not report as failed for not yet supported versions.
This way we can see, how far we are in supporting the later versions.

2016-12-09 13:49 UTC, pfrischmuth requested changes

2016-12-09 13:49 UTC, pfrischmuth commented on .travis.yml
> +        - php: 5.6
We should add PHP 5.6 to the versions, where no failure is accepted.

2016-12-09 15:35 UTC, white-gecko commented
Done

2017-02-03 13:30 UTC, pfrischmuth approved these changes
LGTM

2017-02-03 13:30 UTC, merged