Enable Travis for all Tests
AKSW/Erfurt pull request #141
Opened 2017-02-09 20:03 UTC by shinobu

This pullrequest enables the integration tests for Erfurt.

2017-02-10 13:13 UTC, white-gecko requested changes

2017-02-10 13:13 UTC, white-gecko commented on library/Erfurt/config.ini-dist-mysql
> +store.zenddb.password = ''
Please revert these changes

2017-02-10 13:13 UTC, white-gecko commented on .travis.yml
> +  - cp ./tests/config.ini.dist.travis ./tests/config.ini.dist
The file should be copied to `./tests/config.ini`

2017-02-10 13:13 UTC, white-gecko commented on .travis.yml
> +  - '7.1'
Please don't do such changes.

2017-02-10 13:13 UTC, white-gecko commented on tests/scripts/travis/README.md
> +The unsupported services are marked with *Endabled* "No".
It would be good if you can also fix this typo

2017-02-10 13:13 UTC, white-gecko commented on tests/scripts/travis/README.md
> +		<th>Endabled</th>
same here

2017-02-10 13:13 UTC, white-gecko commented on tests/scripts/travis/install-extensions.sh
> +#!/bin/bash
Please copy these files as they are in one commit and apply your changes in a second commit

2017-02-10 16:07 UTC, shinobu commented
those changes should fix the issues @white-gecko @pfrischmuth

2017-02-10 16:27 UTC, white-gecko commented
@shinobu I've added another commit to get the travis file consistent. Please squash this into on of your commits. So we have two commits in the end.

2017-02-10 16:30 UTC, white-gecko commented
The final changes (ignoring whitespace) are here: https://github.com/AKSW/Erfurt/pull/141/files?w=1

2017-02-10 16:32 UTC, shinobu commented
done @white-gecko

2017-02-17 12:44 UTC, white-gecko approved these changes

2017-02-17 12:45 UTC, merged